title: The Lanzara Group
email: chstan@berkeley.edu
author: Lanzara Group Members
description: >-
  The Lanzara Research Group,
  Ultrafast Photoemission and Optical Spectroscopies of Quantum Materials
baseurl: "chstan/lanzara-staging" # This needs to match the value from the Jekyll repo
url: "https://pages.github.berkeley.edu"

exclude:
  - JEKYLL_REPO_GIT_COMMIT
  - README.md